analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - attributes
  - closure_body_length
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_length
  - file_name
  - file_types_order
  - force_unwrapping
  - function_default_parameter_at_end
  - function_body_length
  - indentation_width
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_grouping_extension
  - no_magic_numbers
  - number_separator
  - one_declaration_per_file
  - prefer_nimble
  - prefixed_toplevel_constant
  - redundant_self_in_closure
  - required_deinit
  - sorted_enum_cases
  - strict_fileprivate
  - superfluous_else
  - switch_case_alignment
  - switch_case_on_newline
  - todo
  - type_body_length
  - type_contents_order
  - vertical_whitespace_between_cases
custom_rules:
  comment_whitespace:
    name: "Comment Whitespace"
    regex: //\S
    match_kinds: comment
    message: "Comments must begin with a whitespace character"
  spaces_not_tabs:
    name: "Spaces not Tabs"
    regex: ^\t
    message: "Use four spaces, not tabs"
  point_zero:
    name: "Point Zero"
    regex: '(?<!iOS\s)(?<!macOS\s)(?<!\.)\b[\d_]+\.0\b'
    match_kinds:
      - number
      - attribute.builtin
    message: "Don't add a .0 to the end of floating point literals"

cyclomatic_complexity: 12
